### -----------------------------------------
### TESTES DO INCREMENTO: CLIENTES (Atualizado)
### -----------------------------------------

### 1. Fazer Login para renovar o Token (Copie o novo token gerado)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identificador": "Admin",
  "senha": "Root"
}

### 2. Teste: Criar Cliente (Validando inserção sem a senha)
POST http://localhost:3000/api/clientes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6IkRCQSIsImlhdCI6MTc4MjIzMzM2OCwiZXhwIjoxNzgyMjYyMTY4fQ.qwIT-HQTIIYq_G4VbhRH06TGshHkNKMpKkDwjRI5lus

{
  "cpf": "02096959438",
  "nome_completo": "Maria Oliveira",
  "data_nascimento": "1985-10-20",
  "id_endereco": 999
}

### 3. Teste: Listar Clientes (Validando o retorno dos dados)
GET http://localhost:3000/api/clientes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6IkRCQSIsImlhdCI6MTc4MjIzMzM2OCwiZXhwIjoxNzgyMjYyMTY4fQ.qwIT-HQTIIYq_G4VbhRH06TGshHkNKMpKkDwjRI5lus