### -----------------------------------------
### TESTES DO INCREMENTO: CLIENTES (Atualizado)
### -----------------------------------------

### 1. Fazer Login para renovar o Token (Copie o novo token gerado)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identificador": "Admin",
  "senha": "Root"
}

### -----------------------------------------
### TESTES DE PERFIL DE ACESSO (ATENDENTE)
### -----------------------------------------

### 1. Criar o Funcionario ATENDENTE (Requer Token ADMIN)
# Ajuste os campos se a sua tabela de funcionário exigir dados diferentes
POST http://localhost:3000/api/funcionarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6IkRCQSIsImlhdCI6MTc4MjI0NTYyNiwiZXhwIjoxNzgyMjc0NDI2fQ.WV9vf3tuyqFtrpRyJbZshPBnhUNvUWYGfXRni6USOtU

{
  "cpf": "45644561305",
  "nome_completo": "Lucas Atendente",
  "cargo": "atendente",
  "senha": "senhaAtendente123",
  "salario": 2500.00,
  "data_nascimento": "1998-02-10",
  "data_admissao": "2026-06-23",
  "id_endereco": 999,
  "num_ag": 5
}

### 2. Fazer Login como ATENDENTE para pegar o Token dele
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identificador": "30",
  "senha": "senhaAtendente123"
}

### 3. O Teste de Bloqueio: Atendente tentando ABRIR uma Conta
# Copie o token que foi gerado no Passo 2 e cole aqui.
# O resultado OBRIGATÓRIO deve ser o Erro 403 Forbidden.
POST http://localhost:3000/api/contas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhZG9yIjozMCwiY2FyZ28iOiJhdGVuZGVudGUiLCJpYXQiOjE3ODIyNjAzNTgsImV4cCI6MTc4MjI4OTE1OH0.hvP1QMlQ0QbjQ4wBdmzaPiHolY2jx1YjiZ7JaNzH0a4

{
  "num_ag": 5,
  "matricula_gerente": 1,
  "saldo": 100.00,
  "senha": "senhaInvasao456",
  "tipo_conta": "conta_corrente"
}

### -----------------------------------------
### TESTES COMPLEMENTARES DE PERFIL (RBAC)
### -----------------------------------------

### 4. Teste da Rota Compartilhada: Atendente Listando Contas
# Use o MESMO token do Lucas (Atendente) que deu erro 403 no teste anterior.
# O resultado esperado é 200 OK e a lista de contas na tela!
GET http://localhost:3000/api/contas
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZGVudGlmaWNhZG9yIjozMCwiY2FyZ28iOiJhdGVuZGVudGUiLCJpYXQiOjE3ODIyNjAzNTgsImV4cCI6MTc4MjI4OTE1OH0.hvP1QMlQ0QbjQ4wBdmzaPiHolY2jx1YjiZ7JaNzH0a4