### Teste de Login do Administrador
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identificador": "Admin",
  "senha": "Root"
}

### 1. Fazer Login como Admin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identificador": "Admin",
  "senha": "Root"
}
###

### 2. Criar Funcionário (Com permissão)
POST http://localhost:3000/api/funcionarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFkbWluIiwicm9sZSI6IkRCQSIsImlhdCI6MTc4MjE2ODg5OCwiZXhwIjoxNzgyMTk3Njk4fQ.f4q5B-7uOFcJI7V5e9TRYjCVVnFpj7mmlFl8-tpk490

{
  "num_ag": 6,
  "nome_completo": "Teste Lima",
  "senha": "senhaSegurissima123",
  "cargo": "gerente",
  "data_nascimento": "2000-01-01",
  "salario": 8500.00
}
###

